language: c

addons:
  postgresql: 9.3

before_install:
  #- sudo apt-get install -q postgresql-9.3-postgis-2.1
  - sudo apt-get install -q postgresql-server-dev-9.3
  - ls /etc/init /etc/init.d | grep postgres
  # Install schema_triggers
  - hg clone https://bitbucket.org/malloclabs/pg_schema_triggers &&
    cd pg_schema_triggers && make && sudo make install && cd -
  # Preload schema_triggers module
  # NOTE: might change if we make it part of the installcheck instead
  - echo "shared_preload_libraries = 'schema_triggers.so'" |
    sudo tee -a /etc/postgresql/9.3/main/postgresql.conf &&
    sudo service postgresql restart

script:
  - make
  - sudo make install
  - make installcheck || { cat regression.diffs; false; }
