language: c

addons:
  postgresql: 9.3

before_install:
  - sudo apt-get update
  #- sudo apt-get install -q postgresql-9.3-postgis-2.1
  - sudo apt-get update
  - sudo apt-get install -q postgresql-server-dev-9.3
  - sudo apt-get install -q postgresql-plpython-9.3

script:
  - make
  - sudo make install
  - PGOPTIONS='-c client_min_messages=NOTICE' PGUSER=postgres make installcheck ||
    { cat regression.diffs; false; }
