dist: xenial
language: c
sudo: required

env:
  global:
    - PGUSER=postgres
    - PGDATABASE=postgres
    - PGOPTIONS='-c client_min_messages=NOTICE'

  matrix:
    - POSTGRESQL_VERSION="9.5"
    - POSTGRESQL_VERSION="10"
    - POSTGRESQL_VERSION="11"

before_install:
  - sudo service postgresql stop;
  - sudo apt-get remove postgresql* -y
  - sudo apt-get install -y --allow-unauthenticated --no-install-recommends --no-install-suggests postgresql-$POSTGRESQL_VERSION postgresql-client-$POSTGRESQL_VERSION postgresql-server-dev-$POSTGRESQL_VERSION postgresql-common postgresql-$POSTGRESQL_VERSION-postgis* postgis postgresql-plpython-$POSTGRESQL_VERSION
  - echo -e "# TYPE  DATABASE        USER            ADDRESS                 METHOD \nlocal   all             postgres                                trust\nlocal   all             all                                     trust\nhost    all             all             127.0.0.1/32            trust"  | sudo tee /etc/postgresql/$POSTGRESQL_VERSION/main/pg_hba.conf
  - sudo service postgresql restart $POSTGRESQL_VERSION || sudo journalctl -xe

script:
  - make
  - sudo make install
  - make installcheck

after_failure:
  - pg_lsclusters
  - cat regression.out
  - cat regression.diffs
