language: c

before_install:
  - lsb_release -a
  - sudo apt-get purge postgresql-9.1 postgresql-9.2
  - sudo apt-get install -q postgresql-server-dev-9.3
  - sudo apt-get install -q postgresql-9.3-postgis-2.1
  - sudo apt-get install -q postgresql-9.3
  - sudo apt-get install -q postgresql-9.3-client
  - dpkg -l | grep postgresql
  - # Install schema_triggers
  - hg clone https://bitbucket.org/malloclabs/pg_schema_triggers &&
    cd pg_schema_triggers && make && sudo make install && cd -

script:
  - make installcheck || { cat regression.diffs; false; }
